from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

from .config_manager import ConfigManager
from .decision import combine_results
from .detector_2d import VisibleDetector
from .detector_ir import IRDetector
from .image_loader import list_image_files
from .io_controller import IOController
from .logger import InspectionLogger
from .models import BagInspectionResult, DetectionResult, PairRecord
from .pair_matcher import PairMatcher


@dataclass
class RuntimeStats:
    total: int = 0
    ok: int = 0
    ng: int = 0
    last_ng_reason: str = ""
    latest_bag_id: str = ""
    running: bool = False

    @property
    def ng_ratio(self) -> float:
        return 0.0 if self.total == 0 else self.ng / self.total

    def to_dict(self) -> Dict[str, object]:
        return {
            "total": self.total,
            "ok": self.ok,
            "ng": self.ng,
            "ng_ratio": round(self.ng_ratio, 4),
            "last_ng_reason": self.last_ng_reason,
            "latest_bag_id": self.latest_bag_id,
            "running": self.running,
        }


class InspectionService:
    def __init__(self, config_manager: Optional[ConfigManager] = None):
        self.config_manager = config_manager or ConfigManager()
        self.stats = RuntimeStats()
        self._processed_keys: set[str] = set()
        self._refresh_components()

    def _refresh_components(self) -> None:
        cfg = self.config_manager.config
        self.visible_detector = VisibleDetector(cfg["visible"])
        self.ir_detector = IRDetector(cfg["ir"])
        self.matcher = PairMatcher(cfg["pairing"]["max_time_diff_ms"])
        self.io_controller = IOController(cfg["io"])
        self.logger = InspectionLogger(
            self.config_manager.resolve_path(cfg["save"]["log_dir"]),
            self.config_manager.resolve_path(cfg["save"]["ng_image_dir"]),
            self.config_manager.resolve_path(cfg["save"]["annotated_dir"]),
        )

    def reload_config(self) -> None:
        self.config_manager.load()
        self._refresh_components()

    def pair_folders(self, folder_2d: str | Path, folder_ir: str | Path) -> List[PairRecord]:
        pairing_cfg = self.config_manager.config.get("pairing", {})
        visible_files = list_image_files(folder_2d)
        ir_files = list_image_files(folder_ir)
        visible_files = self._filter_pairing_files(
            visible_files,
            pairing_cfg.get("visible_prefixes", []),
            pairing_cfg.get("pair_extensions", []),
        )
        ir_files = self._filter_pairing_files(
            ir_files,
            pairing_cfg.get("ir_prefixes", []),
            pairing_cfg.get("pair_extensions", []),
        )
        return self.matcher.match(visible_files, ir_files)

    def inspect_pair(self, pair: PairRecord, save: bool = True) -> BagInspectionResult:
        if pair.image_2d_path:
            visible_result = self.visible_detector.detect_path(pair.image_2d_path)
        else:
            visible_result = DetectionResult(source="2D", result="NG")
            visible_result.add_reason("2D图像缺失")

        if pair.image_ir_path:
            ir_result = self.ir_detector.detect_path(pair.image_ir_path)
        else:
            ir_result = DetectionResult(source="IR", result="NG")
            ir_result.add_reason("红外图像缺失")

        preliminary = combine_results(pair, visible_result, ir_result)
        io_state = self.io_controller.output(preliminary.final_result, pair.bag_id)
        result = combine_results(pair, visible_result, ir_result, io_state)
        self._update_stats(result)
        if save:
            self.logger.append(result)
        return result

    def inspect_packets(self, frame_id: int, packet_2d: dict, packet_ir: dict, save: bool = True) -> BagInspectionResult:
        """Inspect synchronized camera packets generated by CameraThread."""
        frame_2d = packet_2d.get("frame")
        frame_ir = packet_ir.get("frame")
        visible_result = self.visible_detector.detect(frame_2d) if frame_2d is not None else DetectionResult(source="2D", result="NG")
        ir_result = self.ir_detector.detect(frame_ir) if frame_ir is not None else DetectionResult(source="IR", result="NG")
        if frame_2d is None:
            visible_result.add_reason("2D相机取图为空")
        if frame_ir is None:
            ir_result.add_reason("红外相机取图为空")

        path_2d = Path(packet_2d["file_path"]) if packet_2d.get("file_path") else None
        path_ir = Path(packet_ir["file_path"]) if packet_ir.get("file_path") else None
        ts_2d = datetime.fromtimestamp(packet_2d.get("timestamp", 0)) if packet_2d.get("timestamp") else None
        ts_ir = datetime.fromtimestamp(packet_ir.get("timestamp", 0)) if packet_ir.get("timestamp") else None
        diff = None
        if ts_2d and ts_ir:
            diff = abs((ts_2d - ts_ir).total_seconds() * 1000.0)
        pair = PairRecord(
            bag_id=f"BAG{int(frame_id):04d}",
            image_2d_path=path_2d,
            image_ir_path=path_ir,
            timestamp_2d=ts_2d,
            timestamp_ir=ts_ir,
            time_diff_ms=diff,
            status="PAIRED",
        )

        preliminary = combine_results(pair, visible_result, ir_result)
        io_state = self.io_controller.output(preliminary.final_result, pair.bag_id)
        result = combine_results(pair, visible_result, ir_result, io_state)
        self._update_stats(result)
        if save:
            self.logger.append(result)
        return result

    def inspect_folders(self, folder_2d: str | Path, folder_ir: str | Path, save: bool = True) -> List[BagInspectionResult]:
        pairs = self.pair_folders(folder_2d, folder_ir)
        return [self.inspect_pair(pair, save=save) for pair in pairs]

    def inspect_new_pairs(self, folder_2d: str | Path, folder_ir: str | Path, save: bool = True) -> List[BagInspectionResult]:
        results = []
        for pair in self.pair_folders(folder_2d, folder_ir):
            key = f"{pair.image_2d_path}|{pair.image_ir_path}|{pair.status}"
            if key in self._processed_keys:
                continue
            self._processed_keys.add(key)
            results.append(self.inspect_pair(pair, save=save))
        return results

    def _update_stats(self, result: BagInspectionResult) -> None:
        self.stats.total += 1
        self.stats.latest_bag_id = result.pair.bag_id
        if result.final_result == "OK":
            self.stats.ok += 1
        else:
            self.stats.ng += 1
            self.stats.last_ng_reason = "; ".join(result.ng_reasons)

    @staticmethod
    def _filter_pairing_files(files: List[Path], prefixes: List[str], extensions: List[str]) -> List[Path]:
        normalized_prefixes = tuple(prefix.lower() for prefix in prefixes if prefix)
        normalized_extensions = {ext.lower() if ext.startswith(".") else f".{ext.lower()}" for ext in extensions if ext}

        filtered = []
        for path in files:
            if normalized_extensions and path.suffix.lower() not in normalized_extensions:
                continue
            if normalized_prefixes and not path.name.lower().startswith(normalized_prefixes):
                continue
            filtered.append(path)
        return filtered
